##name
spring.application.name=artquiz
##BBDD
spring.datasource.url=jdbc:postgresql://localhost:5432/artquiz_db
spring.datasource.username=Master
spring.datasource.password=Admin123*.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
